import { Training, TrainingMenu, TrainingCategory } from '../types'

// 種目一覧
export const useQueryTrainingList = (): Training[] => {
  return [
    {
      id: 1,
      name: 'ベンチプレス',
      repetitionMax: 50,
      times: 12,
      weight: 40,
      latestTimes: 8,
      latestWeight: 40,
      category: '胸',
    },
    {
      id: 1,
      name: 'ベンチプレス',
      repetitionMax: 50,
      times: 12,
      weight: 40,
      latestTimes: 8,
      latestWeight: 40,
      category: '胸',
    },
    {
      id: 1,
      name: 'ベンチプレス',
      repetitionMax: 50,
      times: 12,
      weight: 40,
      latestTimes: 8,
      latestWeight: 40,
      category: '胸',
    },
    {
      id: 1,
      name: 'ベンチプレス',
      repetitionMax: 50,
      times: 12,
      weight: 40,
      latestTimes: 8,
      latestWeight: 40,
      category: '胸',
    },
    {
      id: 1,
      name: 'ベンチプレス',
      repetitionMax: 50,
      times: 12,
      weight: 40,
      latestTimes: 8,
      latestWeight: 40,
      category: '胸',
    },
  ]
}

// 本日のトレーニングメニュー
export const useQueryDayTrainingMenu = (): TrainingMenu => {
  return {
    name: '胸・背中のメニュー',
    trainingList: [
      {
        id: 1,
        name: 'ベンチプレス',
        repetitionMax: 50,
        times: 12,
        weight: 40,
        latestTimes: 8,
        latestWeight: 40,
        category: '胸',
      },
      {
        id: 1,
        name: 'ベンチプレス',
        repetitionMax: 50,
        times: 12,
        weight: 40,
        latestTimes: 8,
        latestWeight: 40,
        category: '胸',
      },
      {
        id: 1,
        name: 'ベンチプレス',
        repetitionMax: 50,
        times: 12,
        weight: 40,
        latestTimes: 8,
        latestWeight: 40,
        category: '胸',
      },
      {
        id: 1,
        name: 'ベンチプレス',
        repetitionMax: 50,
        times: 12,
        weight: 40,
        latestTimes: 8,
        latestWeight: 40,
        category: '胸',
      },
    ],
  }
}

// 種目一覧をメニューごとにソート
export const useQueryTrainingMenuList = (): TrainingMenu[] => {
  return [
    {
      name: '胸・背中のメニュー',
      trainingList: [
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
      ],
    },
    {
      name: '脚のメニュー',
      trainingList: [
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
      ],
    },
    {
      name: '肩・腕のメニュー',
      trainingList: [
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
      ],
    },
  ]
}

// 種目一覧をカテゴリーごとにソート
export const useQueryTrainingCategoryList = (): TrainingCategory[] => {
  return [
    {
      name: '胸',
      trainingList: [
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
      ],
    },
    {
      name: '背中',
      trainingList: [
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
      ],
    },
    {
      name: '肩',
      trainingList: [
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
        {
          id: 1,
          name: 'ベンチプレス',
          repetitionMax: 50,
          times: 12,
          weight: 40,
          latestTimes: 8,
          latestWeight: 40,
          category: '胸',
        },
      ],
    },
  ]
}
